### ISSUE TITLE
A question about GGen(λ)

### ISSUE THREAD

**Issue by gogo9th** [cambrian/accumulator-demo#4]
Hi,

I'm a PhD student who read Dan's hash accumulator paper and I am very glad to find your source code. Thanks very much. I'd like to leverage your program for my application. But I have just one question. I wonder how you implemented generating the group of an unknown order: G = GGen(λ). I see you added "use accumulator::group::UnknownOrderGroup;". But is this an external library you use?

**Comment by whaatt** [comment]
Hi @gogo9th, and thanks for the question!

The crate being referenced is actually [here](https://github.com/cambrian/accumulator), and this repository is just a demo of how to use that crate. Please let me know if you have trouble finding anything further.

**Comment by gogo9th** [comment]
Hi whaatt, 

Thanks very much for your quick and kind reply. I will look into that link. Have a nice day!
